- name: Restart datastore config server
  community.general.supervisorctl:
    name: datastore-config-server
    state: restarted
    supervisorctl_path: /opt/miniconda/bin/supervisorctl

- name: Restart webserver
  ansible.builtin.service:
    name: httpd
    state: restarted

- name: Restart supervisord
  ansible.builtin.service:
    name: supervisord
    state: restarted
  become: true
