- name: Restart datastore config server
  community.general.supervisorctl:
    name: datastore-config-server
    state: restarted

- name: Restart webserver
  ansible.builtin.shell:
    cmd: "sudo systemctl restart httpd"

- name: Restart supervisord
  ansible.builtin.service:
    name: supervisord
    state: restarted
  become: true
