- name: Restart supervisord
  ansible.builtin.shell:
    cmd: "killall -w supervisord; {{ datastore_venv }}/bin/supervisord -c {{ supervisord_path }}/supervisord.conf"

- name: Restart uWSGI
  community.general.supervisorctl:
    name: uwsgi
    state: restarted
    config: "{{ supervisord_path }}/supervisord.conf"

- name: Restart datastore config server
  community.general.supervisorctl:
    name: datastore-config-server
    state: restarted
    config: "{{ supervisord_path }}/supervisord.conf"

- name: Restart webserver
  ansible.builtin.shell:
    cmd: "sudo systemctl restart httpd"
