---

- name: restart datastore config server
  supervisorctl:
    name: datastore-config-server
    state: restarted
    supervisorctl_path: /opt/miniconda/bin/supervisorctl

- name: restart uWSGI
  supervisorctl:
    name: uwsgi
    state: restarted
    supervisorctl_path: /opt/miniconda/bin/supervisorctl

- name: restart supervisord
  service:
    name: supervisord
    state: restarted
  become: true
