- name: restart datastore config server
  community.general.supervisorctl:
    name: datastore-config-server
    state: restarted
    supervisorctl_path: /opt/miniconda/bin/supervisorctl

- name: restart uWSGI
  community.general.supervisorctl:
    name: uwsgi
    state: restarted
    supervisorctl_path: /opt/miniconda/bin/supervisorctl

- name: restart supervisord
  ansible.builtin.service:
    name: supervisord
    state: restarted
  become: true
