- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted
  become: true

- name: restart openvpn
  when: is_dev is not defined
  service:
    name: "openvpn@{{ item }}.service"
    state: restarted
  with_items:
    - admin
    - client
  become: true
  notify: restart shorewall

- name: restart shorewall
  service:
    name: shorewall
    state: restarted
  become: true
