- name: restart dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: restarted
  become: true

- name: restart openvpn
  ansible.builtin.service:
    name: "openvpn@{{ item }}.service"
    state: restarted
  with_items:
    - admin
    - client
  become: true
  notify: restart shorewall

- name: restart shorewall
  ansible.builtin.service:
    name: shorewall
    state: restarted
  become: true
