- name: Use custom .bashrc
  ansible.builtin.template:
    src: bashrc
    dest: ~/.bashrc
    backup: yes

- name: Ensure publicdb directory exists
  ansible.builtin.file:
    path: "{{ publicdb_path }}"
    state: directory
    mode: 02775

- name: Ensure publicdb log directory exists
  ansible.builtin.file:
    path: "{{ publicdb_logs }}"
    state: directory
    mode: 02775

- name: Ensure hisparc-*.log exists
  ansible.builtin.file:
    path: "{{ publicdb_logs }}/{{ item }}"
    state: touch
    mode: 0644
  with_items:
    - hisparc-update.log
    - hisparc-django-errors.log

- name: "Checkout publicdb in {{ publicdb_code }}"
  ansible.builtin.git:
    repo: "{{ publicdb_repo }}"
    dest: "{{ publicdb_code }}"
    update: yes
    force: no
    version: master
  notify: Restart webserver

- name: Remove compiled python code
  ansible.builtin.command:
    cmd: "find {{ publicdb_code }} -name *.pyc -delete"

- name: "Checkout jsparc in {{ jsparc_path }}"
  ansible.builtin.git:
    repo: "{{ jsparc_repo }}"
    dest: "{{ jsparc_path }}"
    update: yes
    force: no
    version: master

- name: Create django static folder
  ansible.builtin.file:
    path: "{{ publicdb_static }}"
    state: directory

- name: Create django media/raw_data folder
  ansible.builtin.file:
    path: "{{ publicdb_media }}/raw_data"
    state: directory

- name: Copy conda requirements files
  ansible.builtin.copy:
    src: conda.list
    dest: ~/conda.list

- name: Copy pip requirements files
  ansible.builtin.copy:
    src: pip.list
    dest: ~/pip.list

- name: Create conda environment
  ansible.builtin.shell:
    cmd: "{{ miniconda_path }}/bin/conda create -n publicdb_venv python={{ publicdb_python_version }} --yes"
    creates: "{{ publicdb_venv }}"

- name: Install conda packages in conda environment
  ansible.builtin.command:
    cmd: "{{ miniconda_path }}/bin/conda install -n publicdb_venv --channel conda-forge --file ~/conda.list --yes"

- name: Install packages in conda environment using pip
  ansible.builtin.pip:
    requirements: ~/pip.list
    executable: "{{ publicdb_venv }}/bin/pip"

- name: Setup the publicdb database in PostgreSQL
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ psql_database_name }}"
    encoding: UTF-8
    state: present
  vars:
    ansible_python_interpreter: "{{ publicdb_venv }}/bin/python"
  tags: wip

- name: Add hisparc user to the publicdb database
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    db: "{{ psql_database_name }}"
    name: "{{ ansible_user }}"
    priv: ALL
  vars:
    ansible_python_interpreter: "{{ publicdb_venv }}/bin/python"
  tags: wip

- name: Ensure hisparc user has no unnecessary privileges
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ ansible_user }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB
  vars:
    ansible_python_interpreter: "{{ publicdb_venv }}/bin/python"
  tags: wip

- name: Copy Django settings file
  ansible.builtin.template:
    src: settings.py
    dest: "{{ publicdb_code }}/publicdb/settings.py"
    backup: yes
  notify: Restart webserver

- name: Migrate Django apps
  community.general.django_manage:
    command: migrate
    app_path: "{{ publicdb_code }}"
  environment:
    PATH: "{{ publicdb_venv }}/bin:{{ ansible_env.PATH }}"

- name: Collect static files of Django apps
  community.general.django_manage:
    command: collectstatic
    app_path: "{{ publicdb_code }}"
  environment:
    PATH: "{{ publicdb_venv }}/bin:{{ ansible_env.PATH }}"

#### TODO: set up Apache / mod_wsgi

- name: Enable cron job for updating histograms and ESD
  ansible.builtin.cron:
    name: "HiSPARC update"
    minute: 0
    hour: 4
    state: present
    job: "{{ publicdb_venv }}/bin/python {{ publicdb_code }}/manage.py updatehistograms"

- name: Enable cron job for cleaning out downloaded raw_data files
  ansible.builtin.cron:
    name: "clean downloaded data"
    special_time: daily
    state: present
    job: "find {{ publicdb_media }}/raw_data/ -name 'tmp*.h5' -mtime +1 -delete"

- name: Enable cron job for creating analysis sessions
  ansible.builtin.cron:
    name: "create confirmed sessions"
    minute: "*/2"
    # For now, disable. Re-enable when everything works and analysis sessions are planned.
    state: absent
    job: "{{ publicdb_venv }}/bin/python {{ publicdb_code }}manage.py createsessions"

- name: Enable cron job for daily backup of publicdb database
  ansible.builtin.cron:
    name: "Publicdb dump"
    minute: 0
    hour: 1
    state: present
    job: "if [ -f '{{ publicdb_dumps }}/publicdb_dump.sql' ]; then mv {{ publicdb_dumps }}/publicdb_dump.sql {{ publicdb_dumps }}/publicdb_dump_yesterday.sql; fi; pg_dump --format=c --compress=1 --schema=public --dbname=publicdb --file={{ publicdb_dumps }}/publicdb_dump.sql"

- name: Enable cron job for monthly backup of publicdb database
  ansible.builtin.cron:
    name: "Monthly publicdb dump"
    minute: 0
    hour: 20
    day: 1
    state: present
    job: "if [ -f '{{ publicdb_dumps }}/publicdb_dump_this_month.sql' ]; then mv {{ publicdb_dumps }}/publicdb_dump_this_month.sql {{ publicdb_dumps }}/publicdb_dump_prev_month.sql; fi; pg_dump --format=c --compress=1 --schema=public --dbname=publicdb --file={{ publicdb_dumps }}/publicdb_dump_this_month.sql"
