# hisparc needs specific uid:gid for NFS to work.
- name: Check if hisparc has uid=7712
  ansible.builtin.shell: "id -u hisparc"
  register: hisparc_uid
  failed_when: hisparc_uid.stdout != "7712"

- name: Check if hisparc has gid=7100
  ansible.builtin.shell: "id -g hisparc"
  register: hisparc_gid
  failed_when: hisparc_gid.stdout != "7100"

- name: Add SSH keys for hisparc user
  ansible.posix.authorized_key:
    user: hisparc
    key: "{{ item }}"
  with_file:
    - public_keys/adelaat.pub
    - public_keys/davidf.pub
    - public_keys/kaspervd.pub
    - public_keys/tkooij.pub
    - public_keys/tond.pub
    - public_keys/danielk.pub

- name: Upgrade all packages
  ansible.builtin.yum:
    name: "*"
    state: latest
  become: true

- name: Flag a reboot if necessary
  ansible.builtin.script: flag_reboot.sh
  register: result
  changed_when: result.rc == 0
  failed_when: result.rc >= 2
  notify: reboot

- name: Install epel-release package
  ansible.builtin.yum:
    name: epel-release
  become: true

- name: Install ACL utilities
  ansible.builtin.yum:
    name: acl
  become: true

- name: Install screen
  ansible.builtin.yum:
    name: screen
  become: true

# Install mailcap for the mime.types file
- name: Install mailcap
  ansible.builtin.yum:
    name: mailcap
  become: true

- name: Install troubleshooting tools
  ansible.builtin.yum:
    name:
      - nmap
      - tcpdump
      - conntrack-tools
  become: true

- name: Install SELinux tools
  ansible.builtin.yum:
    name:
      - setroubleshoot
      - setools
      - policycoreutils-python
  become: true
