- name: Add SSH keys for hisparc user
  ansible.posix.authorized_key:
    user: hisparc
    key: "{{ item }}"
  with_file:
    - public_keys/adelaat.pub
    - public_keys/davidf.pub
    - public_keys/kaspervd.pub
    - public_keys/tkooij.pub
