---

- name: ensure /usr/local/bin is in sudoers
  lineinfile:
    dest: /etc/sudoers
    regexp: 'secure_path'
    line: "Defaults    secure_path = /opt/miniconda/bin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
    state: present
  become: true

- name: ensure /usr/local/lib is in ld.so.conf
  lineinfile:
    dest: /etc/ld.so.conf
    regexp: '/usr/local/lib'
    line: '/usr/local/lib'
    state: present
  become: true

- name: ensure local source directory exists
  file:
    path: /usr/local/src/hisparc
    state: directory
    owner: hisparc
    group: hisparc
    mode: 02775
  become: true

- name: set default group write ACLs on /usr/local/src/hisparc
  acl:
    default: yes
    etype: group
    permissions: rwx
    path: /usr/local/src/hisparc
    state: present
  become: true

- name: install libraries
  yum:
    name:
      - gcc
      - bzip2
      - make
      - gcc-c++
      - libSM
      - libXrender
      - libXext
      - fontconfig
      - pcre-devel
    state: present
  become: true

- name: download miniconda installer
  get_url:
    url: "https://repo.continuum.io/miniconda/Miniconda2-{{ development_conda_version }}-Linux-x86_64.sh"
    dest: "/usr/local/src/hisparc/Miniconda2-{{ development_conda_version }}-Linux-x86_64.sh"
    checksum: "{{ development_conda_md5 }}"

- name: install miniconda
  command: "/bin/sh /usr/local/src/hisparc/Miniconda2-{{ development_conda_version }}-Linux-x86_64.sh -b -p /opt/miniconda"
  args:
    creates: /opt/miniconda
  become: true

- name: ensure miniconda is in path
  lineinfile:
    dest: /etc/profile.d/path.sh
    create: yes
    mode: 0644
    regexp: 'miniconda'
    line: 'PATH=/opt/miniconda/bin:$PATH'
  become: true

- name: install pip
  command: "/opt/miniconda/bin/conda install pip conda={{ development_conda_version }} --yes"
  become: true

- name: install git
  yum:
    name: git
    state: present
  become: true
