- name: Ensure /usr/local/bin is in sudoers
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    regexp: 'secure_path'
    line: "Defaults    secure_path = /opt/miniconda/bin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
    state: present
  become: true

- name: Ensure /usr/local/lib is in ld.so.conf
  ansible.builtin.lineinfile:
    dest: /etc/ld.so.conf
    regexp: '/usr/local/lib'
    line: '/usr/local/lib'
    state: present
  become: true

- name: Ensure local source directory exists
  ansible.builtin.file:
    path: /usr/local/src/hisparc
    state: directory
    owner: hisparc
    group: hisparc
    mode: 02775
  become: true

- name: Set default group write ACLs on /usr/local/src/hisparc
  ansible.posix.acl:
    default: yes
    etype: group
    permissions: rwx
    path: /usr/local/src/hisparc
    state: present
  become: true

- name: Install libraries
  ansible.builtin.yum:
    name:
      - gcc
      - bzip2
      - make
      - gcc-c++
      - libSM
      - libXrender
      - libXext
      - fontconfig
      - pcre-devel
    state: present
  become: true

- name: Download miniconda installer
  ansible.builtin.get_url:
    url: "https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"
    dest: "/usr/local/src/hisparc/Miniconda3-latest-Linux-x86_64.sh"

- name: Install miniconda
  ansible.builtin.shell:
    cmd: "/usr/local/src/hisparc/Miniconda3-latest-Linux-x86_64.sh -b -p /opt/miniconda"
    creates: /opt/miniconda
  become: true

- name: Ensure miniconda is in path
  ansible.builtin.lineinfile:
    dest: /etc/profile.d/path.sh
    create: yes
    mode: 0644
    regexp: 'miniconda'
    line: 'PATH=/opt/miniconda/bin:$PATH'
  become: true

- name: Install pip
  ansible.builtin.command:
    cmd: "/opt/miniconda/bin/conda install pip --yes"
  become: true

- name: Install git
  ansible.builtin.yum:
    name: git
    state: present
  become: true
