---
- name: Enable firewalld
  service: name=firewalld state=started enabled=yes
  become: true

- name: Set dmz as default policy
  command: firewall-cmd --set-default-zone=dmz
  become: true

- name: Allow http/https
  command: firewall-cmd --zone=dmz --permanent --add-service=http --add-service=https
  become: true

- name: add HTTPS access to firewall rules
  lineinfile:
    dest: /etc/sysconfig/system-config-firewall
    regexp: '--service=https'
    line: '--service=https'
    state: present
  become: true
  notify: compile firewall rules

- name: add XMLRPC access to firewall rules
  command: firewall-cmd --zone=dmz --permanent --add-port=8001/tcp
  become: true

- name: Restart firewalld
  service: name=firewalld state=restarted
  become: true
