- name: Enable firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes
  become: true

- name: Set dmz as default policy
  ansible.builtin.command:
    cmd: firewall-cmd --set-default-zone=dmz
  become: true

- name: Allow http/https
  ansible.builtin.command:
    cmd: firewall-cmd --zone=dmz --permanent --add-service=http --add-service=https
  become: true

- name: add XMLRPC access to firewall rules
  ansible.builtin.command:
    cmd: firewall-cmd --zone=dmz --permanent --add-port=8001/tcp
  become: true

- name: Restart firewalld
  ansible.builtin.service:
    name: firewalld
    state: restarted
  become: true
