- name: install certbot
  ansible.builtin.yum:
    name:
      - certbot
      - python2-certbot-nginx
  become: true

# run "certbot --nginx -n --cert-name data.hisparc.nl -d data.hisparc.nl"
# or restore /etc/letsencrypt from backup
- name: check if letsencrypt is installed or restored from backup
  ansible.builtin.stat:
    path: /etc/letsencrypt
  register: le_dir
  failed_when: le_dir.stat.isdir is defined and not le_dir.stat.isdir

- name: copy letsencrypt https 443 configuration
  ansible.builtin.copy:
    src: nginx-https.conf
    dest: /etc/nginx/conf.d/
  notify: restart nginx
  become: true

# fix path for certbot to work (github issue gh-277)
- name: Set PATH on top of crontab
  ansible.builtin.cron:
    name: PATH
    cron_file: hisparc
    env: yes
    job: "/opt/miniconda/bin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
  become: true

- name: enable cron job for certificate renewal
  ansible.builtin.cron:
    name: "certbot renew twice a day"
    cron_file: hisparc
    minute: "0"
    hour: "0,12"
    state: present
    user: root
    job: "python -c 'import random; import time; time.sleep(random.random() * 3600)' && certbot renew"
  become: true

- name: enable cron job for daily backup of letsencrypt
  ansible.builtin.cron:
    name: "Daily /etc/letsencrypt backup"
    cron_file: hisparc
    minute: 0
    hour: 2
    state: present
    user: root
    job: "if [ -f '/mysqldumps/letsencrypt.tgz' ]; then mv /mysqldumps/letsencrypt.tgz /mysqldumps/letsencrypt_yesterday.tgz; fi; tar czfP /mysqldumps/letsencrypt.tgz /etc/letsencrypt"
  become: true

- name: enable cron job for monthly backup of letsencrypt
  ansible.builtin.cron:
    name: "Monthly /etc/letsencrypt backup"
    cron_file: hisparc
    minute: 0
    hour: 21
    day: 1
    state: present
    user: root
    job: "if [ -f '/mysqldumps/letsencrypt_this_month.tgz' ]; then mv /mysqldumps/letsencrypt_this_month.tgz /mysqldumps/letsencrypt_prev_month.tgz; fi; tar czfP /mysqldumps/letsencrypt_this_month.tgz /etc/letsencrypt"
  become: true
