language: python
python:
  - "2.7"

sudo: false

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda create --yes -n build_env python=$TRAVIS_PYTHON_VERSION
  - source activate build_env
  - pip install -r requirements-dev.txt

script:
  - cp publicdb/settings_develop.py publicdb/settings.py
  - make test

before_deploy:
  - touch doc/_build/html/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: doc/_build/html
  email: beheer@hisparc.nl
  name: HiSPARC-Bot
  on:
    branch: master
    python: 2.7
