version: '3.3'
services:

  postgres:
    image: 'postgres:9.6-alpine'
    restart: unless-stopped
    environment:
      POSTGRES_DB: publicdb
      POSTGRES_USER: hisparc
      POSTGRES_PASSWORD: postgres
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    ports:
      - '54321:5432'

  publicdb:
    image: publicdb
    build: .
    restart: unless-stopped
    environment:
      DJANGO_SETTINGS_MODULE: publicdb.settings_docker
    volumes:
      - '.:/base:ro'
    ports:
      - '8000:8000'
    working_dir: '/base'
    command: './manage.py runserver 0:8000'
    stdin_open: true
    tty: true
    depends_on:
      - postgres
    ports:
      - '8000:8000'

  vpn:
     image: 'python:3.8'
     restart: unless-stopped
     volumes:
       - './scripts:/base:ro'
     ports:
       - '8001:8001'
     working_dir: '/base'
     command: 'python fake-vpn-xmlrpc-server.py'

  datastore:
     image: 'python:3.8'
     restart: unless-stopped
     volumes:
       - './scripts:/base:ro'
     ports:
       - '8002:8002'
     working_dir: '/base'
     command: 'python fake-datastore-xmlrpc-server.py'

volumes:
  pgdata:
