---
- hosts: publicdb
  tasks:
    - name: ensure hisparc user is present
      user: name=hisparc state=present
      sudo: yes

    - name: ensure vagrant user is part of hisparc group
      user: name=vagrant groups=hisparc append=yes
      sudo: yes

    - name: kill active ssh connection (designed to FAIL)
      script: kill_active_sshd.sh
      ignore_errors: true

    - name: enable EPEL repositories
      command: /bin/rpm -U --force http://dl.fedoraproject.org/pub/epel/5/i386/epel-release-5-4.noarch.rpm
      sudo: yes

    - name: ensure /usr/local/lib is in ld.so.conf
      lineinfile: dest=/etc/ld.so.conf regexp=''
                  state=present line='/usr/local/lib' backrefs=yes
      sudo: yes

    - name: ensure local source directory exists
      file: path=/usr/local/src/hisparc state=directory
            owner=hisparc group=hisparc mode=775
      sudo: yes

    - name: download python 2.7 source
      get_url: url=http://www.python.org/ftp/python/2.7.5/Python-2.7.5.tar.bz2
               dest=/usr/local/src/hisparc/

    - name: unpack python 2.7
      shell: chdir=/usr/local/src/hisparc
             creates=/usr/local/src/hisparc/Python-2.7.5
             tar xjf Python-2.7.5.tar.bz2

    - name: build and install python 2.7
      shell: chdir=/usr/local/src/hisparc/Python-2.7.5
             creates=/usr/local/bin/python2.7
             ./configure --enable-shared && make && sudo make install &&
             sudo /sbin/ldconfig

    - name: download setuptools
      get_url: url=https://bitbucket.org/pypa/setuptools/raw/0.8/ez_setup.py
               dest=/usr/local/src/hisparc/

    - name: install setuptools
      shell: chdir=/usr/local/src/hisparc
             creates=/usr/local/bin/easy_install python ez_setup.py
      sudo: yes

    - name: download pip install script
      get_url: url=https://raw.github.com/pypa/pip/master/contrib/get-pip.py
               dest=/usr/local/src/hisparc/

    - name: install pip
      shell: chdir=/usr/local/src/hisparc creates=/usr/local/bin/pip
             python get-pip.py
      sudo: yes

    - name: install virtualenv
      pip: name=virtualenv
      sudo: yes

    - name: download hdf5 1.8 sources
      get_url: url=http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.11.tar.bz2
               dest=/usr/local/src/hisparc/

    - name: unpack hdf5 1.8 sources
      shell: chdir=/usr/local/src/hisparc
             creates=/usr/local/src/hisparc/hdf5-1.8.11
             tar xjf hdf5-1.8.11.tar.bz2

    - name: build and install hdf5 1.8
      shell: chdir=/usr/local/src/hisparc/hdf5-1.8.11
             creates=/usr/local/lib/libhdf5.so.8.0.0
             ./configure --prefix=/usr/local && make && sudo make install
             && sudo /sbin/ldconfig

    - name: install libraries
      yum: name=gcc-gfortran,pkgconfig,lapack-devel,blas-devel,freetype-devel,libpng-devel
      sudo: yes

    - name: ensure /srv directory exists
      file: path=/srv state=directory
      sudo: yes

    - name: ensure /srv/publicdb directory exists
      file: path=/srv/publicdb state=directory
            owner=hisparc group=hisparc mode=775
      sudo: yes

    - name: install python packages in virtualenv
      pip: virtualenv=/srv/publicdb/publicdb_env requirements=/vagrant/req.txt

    - name: install python packages in virtualenv
      pip: virtualenv=/srv/publicdb/publicdb_env requirements=/vagrant/req2.txt

    - name: install python packages in virtualenv
      pip: virtualenv=/srv/publicdb/publicdb_env requirements=/vagrant/req3.txt
