---
- hosts: publicdb
  tasks:
    - name: ensure hisparc user is present
      user: name=hisparc state=present
      sudo: yes

    - name: ensure vagrant user is part of hisparc group
      user: name=vagrant groups=hisparc append=yes
      sudo: yes
