[tool.black]
target-version = ['py310']
line-length = 120
skip-string-normalization = true
extend-exclude = '''
(
    /migrations/
    | /templates/
)
'''

[tool.coverage.run]
branch = true
source = [
    'publicdb',
    'tests',
]
omit = [
    '*/migrations/*',
    'publicdb/settings.py',
]

[tool.coverage.report]
show_missing = true
skip_empty = true
skip_covered = true
