---

- name: Set static networking
  lineinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    regexp: "^{{ item.key }}"
    line: "{{ item.key }}={{ item.value }}"
  with_dict:
    BOOTPROTO: static
    IPADDR: 192.16.186.201
    NETMASK: 255.255.255.0
    ONBOOT: 'yes'
  become: true
  notify: reboot

- name: Set static gateway
  lineinfile:
    dest: /etc/sysconfig/network
    regexp: ^GATEWAY
    line: GATEWAY=192.16.192.80
  become: true
  notify: reboot
