---

- name: reboot
  command: shutdown -r +1 "Ansible triggered a reboot"
  async: 0
  poll: 0
  ignore_errors: true
  notify: wait for server to come back
  become: true

- name: wait for server to come back
  wait_for_connection:
  args:
    delay: 30
