ansible_host: hisparc-data

debug: False

miniconda_path: "{{ hisparc_path }}/publicdb/miniconda"
publicdb_venv: "{{ miniconda_path }}/envs/publicdb_venv"

publicdb_repo: https://github.com/HiSPARC/publicdb.git

psql_database_name: publicdb
psql_user: "{{ ansible_user }}"

# vpn_proxy: "http://{{ vpn_host }}:{{ vpn_port }}"
vpn_proxy:
datastore_proxy: "http://{{ datastore_host }}:{{ datastore_port }}"

email_backend: django.core.mail.backends.smtp.EmailBackend
email_host: smtp.nikhef.nl
email_port: 25

media_url: "https://{{ publicdb_host }}/media/"
static_url: "https://{{ publicdb_host }}/static/"

secret_key: "{{ vault.secret_key }}"
sentry_dsn: "{{ vault.sentry_dsn }}"
