- name: "Ensure {{ hisparc_path }} directory exists"
  ansible.builtin.file:
    path: "{{ hisparc_path }}"
    state: directory

- name: "Ensure {{ datastore_data_path }} directory and subdirectories exist"
  ansible.builtin.file:
    path: "{{ datastore_data_path }}/{{ item }}"
    state: directory
    mode: 02775
  with_items:
    - /
    - tmp
    - incoming
    - partial
    - suspicious
