- name: Ensure /databases directory exists
  ansible.builtin.file:
    path: /databases
    state: directory
  become: true

- name: Ensure /databases/frome directory and subdirectories exist
  ansible.builtin.file:
    path: "/databases/frome/{{ item }}"
    state: directory
    owner: hisparc
    group: hisparc
    mode: 02775
  with_items:
    - /
    - tmp
    - incoming
    - partial
    - suspicious
  become: true
