- name: Ensure /databases directory exists
  ansible.builtin.file:
    path: "{{ hisparc_dir }}"
    state: directory
  become: true

- name: Ensure /databases/raw directory and subdirectories exist
  ansible.builtin.file:
    path: "{{ hisparc_dir }}/raw/{{ item }}"
    state: directory
    owner: hisparc
    group: hisparc
    mode: 02775
  with_items:
    - /
    - tmp
    - incoming
    - partial
    - suspicious
  become: true
