- name: "Ensure {{ hisparc_dir }} directory exists"
  ansible.builtin.file:
    path: "{{ hisparc_dir }}"
    state: directory

- name: "Ensure {{ hisparc_dir }}/raw directory and subdirectories exist"
  ansible.builtin.file:
    path: "{{ hisparc_dir }}/raw/{{ item }}"
    state: directory
    mode: 02775
  with_items:
    - /
    - tmp
    - incoming
    - partial
    - suspicious
