---

# Do not create backups, it will result in many executables in /usr/local/bin
- name: copy vpn/publicdb service scripts
  copy:
    src: vpn-scripts/
    dest: /usr/local/bin
    mode: 0755
  become: true
  notify: restart hisparcvpnd

- name: install pip
  yum:
    name: python-pip
  become: true

- name: install supervisord prerequisites
  yum:
    name: python-meld3
  become: true

- name: install supervisor daemon
  pip:
    name: supervisor
  become: true

- name: copy supervisord init script
  copy:
    src: supervisord
    dest: /etc/init.d/supervisord
    backup: yes
    owner: root
    group: root
    mode: 0755
  become: true

- name: copy supervisord.conf
  copy:
    src: supervisord.conf
    dest: /etc/supervisord.conf
    backup: yes
    owner: root
    group: root
    mode: 0644
  become: true
  notify: restart supervisord

- name: start supervisord now and on boot
  service:
    name: supervisord
    state: started
    enabled: yes
  become: true

- name: start hisparcvpnd
  supervisorctl:
    name: hisparcvpnd
    state: started
