- name: restart uWSGI
  supervisorctl:
    name: uwsgi
    state: restarted
    supervisorctl_path: /opt/miniconda/bin/supervisorctl

- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: true
