- name: Copy PostgreSQL authentication config file
  become: true
  become_user: postgres
  ansible.builtin.template:
    src: pg_hba.conf
    dest: "/usr/pgsql-14/share/pg_hba.conf"
    mode: 0600
  notify: restart postgresql

- name: Start PostgreSQL server now and on boot
  ansible.builtin.service:
    name: "postgresql-{{ psql_version }}"
    state: started
    enabled: yes
  become: true
