- name: Copy PostgreSQL authentication config file
  ansible.builtin.template:
    src: pg_hba.conf
    dest: "/tmp/pg_hba.conf"
  register: postgresconf

- name: Sudoedit PostgreSQL authentication config file
  ansible.builtin.shell:
    cmd: "sudo sudoedit /usr/pgsql-14/share/pg_hba.conf"
    stdin: ":1,$d|:r /tmp/pg_hba.conf|:wq"
  environment:
    SUDO_EDITOR: /usr/bin/vi
  when: postgresconf.changed
  notify: restart postgresql

- name: Flush handlers
  meta: flush_handlers
