- name: Setup prepare Python environment
  hosts: publicdb:datastore
  roles:
    - development

- name: Setup bashrc on shared user account
  hosts: publicdb:datastore
  roles:
    - shared-account

- name: Setup public database server
  hosts: publicdb
  roles:
    - postgresql
    - publicdb

- name: Setup datastore server
  hosts: datastore
  roles:
    - datastore

# Datastore Firewall (nftables)
# HiSPARC datastore configuration server
# ip saddr hisparc-data tcp dport { 8001 } accept
