---
- hosts: all
  tasks:
    - include: common.yml
  handlers:
    - include: handlers.yml

- hosts: publicdb:pique.nikhef.nl
  tasks:
    - include: simple-firewall.yml
    - include: mysqldb.yml
    - include: development.yml
    - include: publicdb.yml
  handlers:
    - include: handlers.yml

- hosts: publicdb
  tasks:
    - include: fake_datastore.yml

- hosts: tietar.nikhef.nl
  tasks:
    - include: network-tietar.yml
  handlers:
    - include: handlers.yml

- hosts: vpn:tietar.nikhef.nl
  tasks:
    - include: mitigate-dos.yml
    - include: postfix.yml
    - include: shorewall-firewall.yml
    - include: openvpn.yml
    - include: nagios.yml
    - include: vpn-scripts.yml
  handlers:
    - include: handlers.yml

- hosts: datastore
  tasks:
   - include: simple-firewall.yml
   - include: development.yml
   - include: datastore.yml
  handlers:
   - include: handlers.yml
