# - name: Common provisioning for all hosts
#   hosts: all
#   roles:
#     - common

- name: Ensure required datastore paths exist
  hosts: publicdb:datastore
  roles:
    - datastore-paths

- name: Setup firewall and development tools are installed
  hosts: publicdb_group:datastore_group
  roles:
    - simple-firewall
    - development

- name: Setup public database server
  hosts: publicdb_group
  roles:
    - postgresql
    - self-signed-cert
    - publicdb

- name: Setup lets encrypt for HTTPS
  hosts: pique.nikhef.nl
  roles:
    - letsencrypt

- name: Setup datastore server
  hosts: datastore_group
  roles:
    - datastore

- name: Setup network config for tietar
  hosts: tietar.nikhef.nl
  roles:
    - network-tietar

- name: Setup VPN server
  hosts: vpn_group
  roles:
    - dos
    - postfix
    - shorewall-firewall
    - openvpn
    - vpn-scripts
