---

- hosts: all
  roles:
    - common

- hosts: publicdb:datastore
  roles:
    - datastore-paths

- hosts: publicdb_group
  roles:
    - simple-firewall
    - postgresql
    - development
    - publicdb

- hosts: tietar.nikhef.nl
  roles:
    - network-tietar

- hosts: vpn_group
  roles:
    - dos
    - postfix
    - shorewall-firewall
    - openvpn
    - nagios
    - vpn-scripts

- hosts: datastore_group
  roles:
    - datastore
    - development
    - simple-firewall
