---

- hosts: all
  roles:
    - common

- hosts: publicdb:datastore
  roles:
    - datastore-paths

- hosts: publicdb_group:datastore_group
  roles:
    - simple-firewall
    - development

- hosts: publicdb_group
  roles:
    - postgresql
    - publicdb

- hosts: datastore_group
  roles:
    - datastore

- hosts: tietar.nikhef.nl
  roles:
    - network-tietar
  handlers:
    - include: roles/network-tietar/handlers/main.yml

- hosts: vpn_group
  roles:
    - dos
    - postfix
    - shorewall-firewall
    - openvpn
    - nagios
    - vpn-scripts
