---

debug: False

publicdb_repo: https://github.com/HiSPARC/publicdb.git

psql_database_name: publicdb
psql_user: "{{ ansible_user }}"

vpn_host: tietar.nikhef.nl
vpn_proxy: http://tietar.nikhef.nl:8001
datastore_host: frome.nikhef.nl
datastore_proxy: http://frome.nikhef.nl:8001

email_backend: django.core.mail.backends.smtp.EmailBackend
email_host: smtp.nikhef.nl
email_port: 25

publicdb_host: http://data.hisparc.nl
media_url: http://data.hisparc.nl/media/
static_url: http://data.hisparc.nl/static/

secret_key: "{{ vault.secret_key }}"
sentry_dsn: "{{ vault.sentry_dsn }}"
