- name: Install shorewall firewall
  ansible.builtin.yum:
    name: shorewall
  become: true

- name: Copy shorewall config
  ansible.builtin.copy:
    src: vpn-shorewall/
    dest: /etc/shorewall
    backup: yes
  become: true
  notify: restart shorewall

- name: Update shorewall configuration
  ansible.builtin.command:
    cmd: shorewall update -A
  become: true
  notify: restart shorewall

- name: Ensure shorewall is started
  ansible.builtin.service:
    name: shorewall
    enabled: yes
    state: started
  become: true
