- name: Install openvpn and dnsmasq
  ansible.builtin.yum:
    name:
      - openvpn
      - openssl
      - dnsmasq
  become: true

- name: Copy dnsmasq config
  ansible.builtin.copy:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf
    backup: yes
  become: true
  notify: restart dnsmasq

- name: Copy openvpn config. Including vendored easy_rsa
  ansible.builtin.copy:
    src: openvpn/
    dest: /etc/openvpn
    backup: yes
  become: true
  notify: restart openvpn

- name: Overwrite systemd openvpn configuration to enable MD5
  ansible.builtin.copy:
    src: openvpn@client.service
    dest: /etc/systemd/system/openvpn@client.service
    backup: yes
  become: true
  notify: restart openvpn

- name: Create private keys
  ansible.builtin.copy:
    content: "{{ item.key }}"
    dest: "/etc/openvpn/{{ item.path }}"
    backup: no
    mode: 0600
  become: true
  notify: restart openvpn
  with_items: "{{ private_keys }}"
  no_log: True

- name: Ensure ccd directory exists
  ansible.builtin.file:
    path: /etc/openvpn/ccd
    state: directory
  become: true
  notify: restart openvpn

- name: Ensure dnsmasq is started
  ansible.builtin.service:
    name: dnsmasq
    enabled: yes
    state: started
  become: true

- name: Ensure openvpn is started
  ansible.builtin.service:
    name: "openvpn@{{ item }}.service"
    enabled: yes
    state: restarted
  with_items:
    - admin
    - client
  become: true

- name: Create nikhef network resolv.conf
  ansible.builtin.lineinfile:
    create: yes
    dest: /etc/resolv.conf-nikhef
    line: "nameserver {{ item }}"
  with_items:
    - 8.8.8.8
    - 8.8.4.4
  become: true

- name: Copy resolv.conf
  ansible.builtin.copy:
    src: resolv.conf
    dest: /etc/resolv.conf
    backup: yes
  become: true

- name: Enable cron job for daily backup of openvpn config and PKI
  ansible.builtin.cron:
    name: "openvpn backup"
    cron_file: root
    minute: 0
    hour: 1
    state: present
    user: root
    job: "if [ -f '/backups/openvpn-backup.tar.gz' ]; then mv /backups/openvpn-backup.tar.gz /backups/openvpn-backup_yesterday.tar.gz; fi; tar czf /backups/openvpn-backup.tar.gz /etc/openvpn"
  become: true

- name: Enable cron job for monthly backup of openvpn config and PKI
  ansible.builtin.cron:
    name: "Monthly openvpn backup"
    cron_file: root
    minute: 0
    hour: 20
    day: 1
    state: present
    user: root
    job: "if [ -f '/backups/openvpn-backup_this_month.tar.gz' ]; then mv /backups/openvpn-backup_this_month.tar.gz /backups/openvpn-backup_previous_month.tar.gz; fi; tar czf /backups/openvpn-backup_this_month.tar.gz /etc/openvpn"
  become: true
