---

- name: install openvpn and dnsmasq
  yum:
    name:
      - openvpn
      - openssl
      - dnsmasq
  become: true

- name: copy dnsmasq config
  copy:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf
    backup: yes
  become: true
  notify: restart dnsmasq

- name: copy openvpn config. Including vendored easy_rsa
  copy:
    src: openvpn/
    dest: /etc/openvpn
    backup: yes
  become: true
  notify: restart openvpn

- name: create private keys
  copy:
    content: "{{ item.key }}"
    dest: "/etc/openvpn/{{ item.path }}"
    backup: no
    mode: 0600
  become: true
  notify: restart openvpn
  with_items: "{{ private_keys }}"
  no_log: True

- name: ensure ccd directory exists
  file:
    path: /etc/openvpn/ccd
    state: directory
  become: true
  notify: restart openvpn

- name: ensure dnsmasq is started
  service:
    name: dnsmasq
    enabled: yes
    state: started
  become: true

- name: ensure openvpn is started
  when: is_dev is not defined
  service:
    name: "openvpn@{{ item }}.service"
    enabled: yes
    state: started
  with_items:
    - admin
    - client
  become: true

- name: create nikhef network resolv.conf
  lineinfile:
    create: yes
    dest: /etc/resolv.conf-nikhef
    line: "nameserver {{ item }}"
  with_items:
    - 192.16.199.17
    - 192.16.185.12
  become: true

- name: copy resolv.conf
  copy:
    src: resolv.conf
    dest: /etc/resolv.conf
    backup: yes
  when: is_dev is not defined
  become: true
