---

- name: reboot
  reboot:
  notify:
    - fail if dev to remount shared folders
  become: true

- name: fail if dev to remount shared folders
  fail:
    msg: Reboot VM with vagrant to remount shared folders and continue provisioning, using `$ vagrant reload --provision [machine]`
  when: is_dev is defined
